title: COVID-19 - Workflow2
resource: ornl.summit
queue: killable
schema_: local
project: CHM155_003
walltime_min: 360
max_iteration: 5
cpus_per_node: 46
gpus_per_node: 6
hardware_threads_per_cpu: 4
experiment_directory: /gpfs/alpine/scratch/nsanjrani/chm155/rqn_run_test
node_local_path: null
molecular_dynamics_stage:
    pre_exec: 
    - module load cuda/10.1.243
    - . /sw/summit/python/3.7/anaconda3/5.3.0/etc/profile.d/conda.sh
    - conda activate /ccs/home/nsanjrani/.conda/envs/conda-ddmd-new
    executable: /ccs/home/nsanjrani/.conda/envs/conda-ddmd-new/bin/python
    arguments: 
          - /ccs/home/nsanjrani/prot_lig_packages/DeepDriveMD-pipeline/deepdrivemd/sim/openmm/run_openmm.py 
    cpu_reqs:
        processes: 1
        process_type: null
        threads_per_process: 4
        thread_type: OpenMP
    gpu_reqs:
        processes: 1
        process_type: null
        threads_per_process: 1
        thread_type: CUDA
    num_tasks: 20
    task_config:
        experiment_directory: set_by_deepdrivemd
        stage_idx: 0
        task_idx: 0
        output_path: set_by_deepdrivemd
        node_local_path: set_by_deepdrivemd
        pdb_file: /ccs/home/nsanjrani/prot_lig_packages/DeepDriveMD-pipeline/3clpro_rqn_unbound/system/3clpro_final_solv.pdb
        initial_pdb_dir: /ccs/home/nsanjrani/prot_lig_packages/DeepDriveMD-pipeline/3clpro_rqn_unbound
        solvent_type: explicit
        top_suffix: .prmtop
        simulation_length_ns: 1.0
        report_interval_ps: 1.0
        dt_ps: 0.002
        temperature_kelvin: 310.0
        heat_bath_friction_coef: 1.0
        wrap: true
        wrap_pdb_file: /ccs/home/nsanjrani/prot_lig_packages/DeepDriveMD-pipeline/3clpro_rqn_unbound/system/3clpro_final_solv.pdb
        reference_pdb_file: /ccs/home/nsanjrani/prot_lig_packages/DeepDriveMD-pipeline/3clpro_rqn_unbound/3clpro_final_solv_bound.pdb
        openmm_selection:
        - CA
        mda_selection: protein and name CA
        mda_lig_selection: resname RQN and not name H*
        threshold: 8
        contact_map: true
        point_cloud: true
        fraction_of_contacts: true
        heavy_atom_contacts: true
        in_memory: false
aggregation_stage:
    pre_exec: []
    executable: ''
    arguments: []
    cpu_reqs:
        processes: 1
        process_type: null
        threads_per_process: 1
        thread_type: null
    gpu_reqs:
        processes: 0
        process_type: null
        threads_per_process: 0
        thread_type: null
    skip_aggregation: true
    task_config:
        experiment_directory: set_by_deepdrivemd
        stage_idx: 0
        task_idx: 0
        output_path: set_by_deepdrivemd
        node_local_path: set_by_deepdrivemd
machine_learning_stage:
    pre_exec:
            - module load gcc/7.5.0
            - module load cuda/10.1.243
            - export LANG=en_US.utf-8
            - export LC_ALL=en_US.utf-8
            - export HDF5_USE_FILE_LOCKING=FALSE
            - export LD_LIBRARY_PATH=/gpfs/alpine/proj-shared/med110/atrifan/scripts/cuda/targets/ppc64le-linux/lib/:$LD_LIBRARY_PATH
            - export OMP_NUM_THREADS=4
    executable: /ccs/home/nsanjrani/.conda/envs/pytorch-env-new/bin/python
    arguments:
            - /ccs/home/nsanjrani/prot_lig_packages/DeepDriveMD-pipeline/deepdrivemd/models/aae/train.py
    cpu_reqs:
        processes: 1
        process_type: null
        threads_per_process: 4
        thread_type: OpenMP
    gpu_reqs:
        processes: 1
        process_type: null
        threads_per_process: 1
        thread_type: CUDA
    retrain_freq: 1
    task_config:
        experiment_directory: set_by_deepdrivemd
        stage_idx: 0
        task_idx: 0
        output_path: set_by_deepdrivemd
        node_local_path: set_by_deepdrivemd
        model_tag: set_by_deepdrivemd
        init_weights_path: /gpfs/alpine/proj-shared/chm155/natasha/rqn/rep1/lig_pc/9/checkpoint/epoch-70-20210823-180008.pt
        last_n_h5_files: 20
        k_random_old_h5_files: 20
        dataset_name: point_cloud
        rmsd_name: rmsd
        fnc_name: heavy_atom_contacts
        num_points: 326
        num_features: 0
        initial_epochs: 70
        epochs: 70
        batch_size: 32
        optimizer_name: Adam
        optimizer_lr: 0.0001
        latent_dim: 64
        encoder_filters:
        - 64
        - 128
        - 256
        - 256
        - 512
        encoder_kernel_sizes:
        - 5
        - 5
        - 3
        - 1
        - 1
        generator_filters:
        - 64
        - 128
        - 512
        - 1024
        discriminator_filters:
        - 512
        - 512
        - 128
        - 64
        encoder_relu_slope: 0.0
        generator_relu_slope: 0.0
        discriminator_relu_slope: 0.0
        use_encoder_bias: true
        use_generator_bias: true
        use_discriminator_bias: true
        noise_mu: 0.0
        noise_std: 1.0
        lambda_rec: 0.5
        lambda_gp: 10.0
        embed_interval: 1
        tsne_interval: 12
        sample_interval: 20
        num_data_workers: 0
        dataset_location: storage
        wandb_project_name: null                
model_selection_stage:
    pre_exec: []
    executable: /ccs/home/nsanjrani/.conda/envs/pytorch-env-new/bin/python
    arguments:
            - /ccs/home/nsanjrani/prot_lig_packages/DeepDriveMD-pipeline/deepdrivemd/selection/latest/select_model.py
    cpu_reqs:
        processes: 1
        process_type: null
        threads_per_process: 4
        thread_type: null
    gpu_reqs:
        processes: 0
        process_type: null
        threads_per_process: 0
        thread_type: null
    task_config:
        experiment_directory: set_by_deepdrivemd
        stage_idx: 0
        task_idx: 0
        output_path: set_by_deepdrivemd
        node_local_path: set_by_deepdrivemd
        retrain_freq: 1
agent_stage:
    pre_exec: 
            - export LANG=en_US.utf-8
            - export LC_ALL=en_US.utf-8
            - unset CUDA_VISIBLE_DEVICES
            - export HDF5_USE_FILE_LOCKING=FALSE
            - export OMP_NUM_THREADS=4
    executable: cat /dev/null; jsrun -n1 -a6 -g6 -r1 -c7 /ccs/home/nsanjrani/prot_lig_packages/DeepDriveMD-pipeline/deepdrivemd/agents/lof/bin/lassen.sh
    arguments: 
            - /ccs/home/nsanjrani/.conda/envs/pytorch-env-new/bin/python
            - /ccs/home/nsanjrani/prot_lig_packages/DeepDriveMD-pipeline/deepdrivemd/agents/lof/lof.py
    cpu_reqs:
        processes: 1
        process_type: null
        threads_per_process: 1
        thread_type: null
    gpu_reqs:
        processes: 1
        process_type: null
        threads_per_process: 1
        thread_type: CUDA
    task_config:
        experiment_directory: set_by_deepdrivemd
        stage_idx: 0
        task_idx: 0
        output_path: set_by_deepdrivemd
        node_local_path: set_by_deepdrivemd
        num_intrinsic_outliers: 100
        num_extrinsic_outliers: 20
        intrinsic_score: lof
        extrinsic_score: heavy_atom_contacts
        n_traj_frames: 1000
        n_most_recent_h5_files: 20
        k_random_old_h5_files: 20
        sklearn_num_jobs: -1
        model_type: "AAE3d"
        inference_batch_size: 128
